name: URL Health Check
on:
  push:
    branches:
      - main
      - part11*
  schedule:
    - cron: '0 0 * * *'
jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v4
        with:
          url: ${{ vars.RENDER_URL }}